sudo: required
services:
  - docker

before_install:
  - docker build -t gatkinso/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gatkinso/react-test npm test -- --coverage

after_success:
  - docker build -t gatkinso/multi-client ./client
  - docker build -t gatkinso/multi-nginx ./nginx
  - docker build -t gatkinso/multi-server ./server
  - docker build -t gatkinso/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Push images to dockerhub
  - docker push gatkinso/multi-client
  - docker push gatkinso/multi-nginx
  - docker push gatkinso/multi-server
  - docker push gatkinso/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-827493697182"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
